### ISSUE TITLE
The RX Fifo should be drained twice on when rx_fifo_drain is called

### ISSUE THREAD

**Issue by leonardxiang** [bespoke-silicon-group/bsg_f1#240]
https://github.com/bespoke-silicon-group/bsg_f1/blob/c295db75fb4444fcd2ddb78ad68a25d5c85336d6/cl_manycore/libraries/bsg_manycore.cpp#L149

The receive fifo before the axi_to_manycore rx fifo has width=128 and depth=256 now.
The axi_to_manycore rx fifo(Xilinx  ip) has depth=514, so we need drain the rx fifo >= 3 times to make it successful.

**Comment by leonardxiang** [comment]
This is relative to #237, to make the failed simulation terminate.

**Comment by drichmond** [comment]
Hi Leonard, I don't understand. What do you mean?

**Comment by leonardxiang** [comment]
I mean that in the s_axil_mcl_adapter module, there is a 256x128 receive fifo before the axi_fifo_mm_s IP.
If we want to drain the rx fifo(I mean the fifo inside the axi_fifo_mm_s), it is not enough to only drain the rx fifo once. We should at least drain the rx fifo 3 times as the receive fifo is 2 times larger than the rx fifo.

**Comment by drichmond** [comment]
I agree that this is an issue - but I think the description is off. In the current implementation, we check the fifo occupancy. This returns the number of locations used by the latest received packet. 

We then drain that packet, and check again. If the first drain was unsuccessful, then we return an error. 

We could try to drain more packets - but at the end of the day, if a previous program left stale data behind then the FPGA image should probably be reloaded. There's no good way to recover from that.

**Comment by drichmond** [comment]
Leonard, is this Xilinx-host-interface specific? 

When we move to BaseJump will this still be an Issue?

**Comment by leonardxiang** [comment]
The basejump version uses the same definition as Xilinx version, so current API will not change.

**Comment by drichmond** [comment]
But do you have a dual-fifo issue what you described above?

**Comment by leonardxiang** [comment]
> But do you have a dual-fifo issue what you described above?

Yes, the issue still exists. I still used receive fifo and rx fifo.

**Comment by drichmond** [comment]
Can you change the fifo sizes so that we only have to drain twice?

**Comment by leonardxiang** [comment]
Sure, I will do that.

**Comment by max-ruttenberg** [comment]
@drichmond I think this was addressed in https://github.com/bespoke-silicon-group/bsg_f1/pull/249?

**Comment by drichmond** [comment]
Do we drain the RX Fifo twice? If not, then no.

**Comment by drichmond** [comment]
The issues is that there are two FIFOs - one for manycore packets (128-bits) and one for the AXI-Lite data (32-bits). If we drain one, it's still possible that the other one has data.

The reason for this architecture is because putting a packet in the AXI-Lite FIFO takes four cycles, while a packet on the manycore network takes one cycle. Having a 128-bit packet fifo prevents packets from being dropped while they are being "serialized"

I've asked leonard to make the Manycore packet FIFO smaller so that we don't have as much outstanding data, but that's only a temporary solution. 

A better solution would be to have a 128-bit FIFO that can be read by AXI lite. The Xilinx IP doesn't support this - and I don't know if Leonard's new AXI Interface does either.
