### ISSUE TITLE
Remove local alloc/free uses of malloc

### ISSUE THREAD

**Issue by drichmond** [bespoke-silicon-group/bsg_f1#269]
https://github.com/bespoke-silicon-group/bsg_f1/blob/12617602a16b781418463f639d31abeb1adae9a0/cl_manycore/libraries/bsg_manycore_cuda.cpp#L758

My possibly flawed opinion is that it's faster (no call to glibc), and less error prone, to stack allocate. 

@max-ruttenberg, your thoughts?

**Comment by max-ruttenberg** [comment]
Stack allocation typically makes for cleaner programming because 
1. You don't have to free it - one less potential bug.
2. Syntactically (I think) it's easier to read. The above line would be re-written like this to stack allocate:
```c
hb_mc_coordinate_t tile_list[num_tiles];
```
3. I would imagine that it would be faster for a couple of reasons. No function call to glibc, stack allocation is typically as trivial as adding a value to your stack pointer, better data locality, etc. 

@drichmond is correct that in the above example there is really no reason why `tile_list` needs to be heap allocated -- It's freed anyway before it would go out of scope. There's a misconception that C requires dynamically sized arrays to be allocated with malloc and friends. It's a nasty misconception that's probably left over from the old days of C. You can use the line shown in (2) to allocate your array on the stack (and you should). 

There **ARE** times to use malloc and friends; 
1. When you want the memory that you're allocating to persist after your function returns.
2. You have a global pointer that you want initialized to point to a dynamically sized buffer.

While this line of code is not a good example of when to use malloc, there are plenty of appropriate uses of malloc in `bsg_manycore_cuda.cpp` so certainly don't try to get rid of **ALL** of them.

**Comment by drichmond** [comment]
Cool. I've updated the title to be more specific

**Comment by drichmond** [comment]
Thanks for the Stack-Overflow like explanation, Max!

**Comment by bornaehsani** [comment]
All of this makes complete sense to me, and thanks a lot for the detailed explanation @max-ruttenberg ! I will iterate the code and remove the unnecessary mallocs like this one.

**Comment by bornaehsani** [comment]
Addressed in PR #275 .
