### ISSUE TITLE
Printing long string(s) with`bsg_printf` causes the F1 instance to hang (v3.0.6)

### ISSUE THREAD

**Issue by avanhatt** [bespoke-silicon-group/bsg_f1#338]
Hi! Excited for `bsg_printf` to now work on the F1 instances with v3.0.6.

When trying to print information from all tiles a 4x4 grid, longer strings (~50 chars) printed from all 16 tiles seem to cause the entire instance to hang until it's reloaded with `fpga-load-local-image`.

Even printing a single longer string (~300 chars) from just the (0,0) tile has unexpected behavior - the string prints multiple times instead of just once, and then again the instance needs to be reloaded to restore expected behavior. 

A minimal example with both functional and problematic string lengths attached. Thanks!

[print-length-bug.zip](https://github.com/bespoke-silicon-group/bsg_f1/files/3378381/print-length-bug.zip)

**Comment by drichmond** [comment]
Hi Alexa

This is definitely a bug! We believe that the root cause is a hardware FIFO overflow on the host interface, but haven't root caused it yet. For the time being, are you able to print smaller strings? 

Max is also working to create a print_int version of printf that will allow lighter-weight debugging and be less susceptible to this problem.

It is possible that #261 solves this, but it doesn't help your current situation.

**Comment by avanhatt** [comment]
Yes, we are able to print smaller strings (about <= 50 chars per tile if printing from all 16 tiles on a 4x4), so we can work around this for the time being. 

Happy to help determine if #261 resolves this issue once that is merged.

Thanks!

**Comment by taylor-bsg** [comment]
Just reiterate Dustin’s point, print_int has the cost of a single store
instruction, so it is often much more useful than bsg_printf, which like
all printf implementations, is a big pile of code.

**Comment by vb000** [comment]
https://github.com/bespoke-silicon-group/bsg_manycore/blob/4a2c5642a56f36196e97412fc178ccc6c8414f0c/software/bsg_manycore_lib/bsg_printf.c#L581

@drichmond @mrutt92 Increasing this seems to fix the issue :no_mouth:. `bsg_printf` can only print strings shorter than 256 chars long?

**Comment by drichmond** [comment]
Hmm. Is that a reasonable limitation? (Open to discussion)

**Comment by vb000** [comment]
One hack is to parameterize it and have make variable to set the size at compile time. 

But a cleaner solution is to dynamically allocate buffer. Either using newlib's malloc as is, or a lightweight custom implementation.

**Comment by drichmond** [comment]
We think this is fixed. But willing to reopen if it comes back

**Comment by taylor-bsg** [comment]
A few questions:

- do we have this as part of our regression suite?

- I imagine that since this implementation takes > 256+80 bytes of stack
storage, we will have the ugly problem that calling printf can cause the
stack to grow over other locally allocated data. This will happen just as
people are starting to reach a level of program size/complexity where they
want to use printf, which will paradoxically stop working mysteriously.
Which brings us back to “don’t use printf!!” :-)

- alternatives:
      1. Allocate static buffers in dram (slow)
      2. Use a macro for character writes in the inner routine to the
internal buffer. Then make that macro just write to the I/O port directly
instead.
      3. Instead of running the code on the tile, just package up the
parameters as an RPC to the host. Then the host can DMA the memory regions
and do the print.

#2 is the easiest but specific to this case.
#3 is the most complicated but could be generalized to handle a lot of
cases.

Possibly the best route is to do #2 and then when we see other uses for #3,
we can look into it?

**Comment by taylor-bsg** [comment]
Random aside: bsg_printf executing on the tile is still likely to have
performance side effects since it may evict a lot of L1 lines.
