### ISSUE TITLE
Add cache to memory read and write test

### ISSUE THREAD

**Issue by leonardxiang** [bespoke-silicon-group/bsg_f1#451]
We now have some library tests case for the cache to lv3 memory:
- test_dram_read_write
- test_manycore_vcache_sequence
- test_vcache_sequence
- test_vcache_stride
As far as I know, these tests read the latest data been written to the cache. 
I guess we need more tests to ensure that the dram has been write and read correctly by each cache column?

**Comment by drichmond** [comment]
Some tests evict data from vcache, but no, in general we do not have tests in library that fully test DRAM

**Comment by drichmond** [comment]
Do we have a SPMD test that does this (@tommydcjung)?

**Comment by drichmond** [comment]
@mrutt92 Does #463 address this, or do we need more tests?

@tommydcjung Is there a SPMD test that we can run to test the cache?

**Comment by mrutt92** [comment]
The most significant thing #463 does is it fixes test_vcache_flush, which wasn't actually doing what it was supposed to because cache parameters were hardcoded as constants rather than being read out of the ROM. As a result, test_vcache_flush was not actually reading from DRAM because it wasn't causing any evictions to occur. Now it actually does write a word of data to DRAM and read it back. AFAICT test_vcache_flush is the only test guaranteed to exercise DRAM in anyway.

The other fixes in #463 are small. test_vcache_sequence was not calculating addresses correctly. Other than that I changed the formatting for how these tests print memory and data to facilitate wave form debugging.

**Comment by mrutt92** [comment]
test_vcache_sequence and test_vcache_stride both write some number of words to column caches and right now they both only exercise one cache. The difference between the two tests is that test_vcache_sequence writes to a contiguous region where as test_vcache_stride spaces the words out by a constant stride distance. It seems to me that neither test guarantees that valid data will be written to DRAM and then read back.

**Comment by drichmond** [comment]
I thought one of the tests evicted data, maybe I was mistaken.

**Comment by tommydcjung** [comment]
I don't think there is any spmd test to do that.

**Comment by drichmond** [comment]
I believe this was addressed in #468.
